// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPSRHCL2WvMlWwJjxx7WFNTzXRn05rb8s',
    appId: '1:543606157745:web:8d1edf76ad197a875d8d90',
    messagingSenderId: '543606157745',
    projectId: 'agenteste-3a825',
    authDomain: 'agenteste-3a825.firebaseapp.com',
    storageBucket: 'agenteste-3a825.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4IcEKDUliRfseZHUP7sszwodpy08TIDA',
    appId: '1:543606157745:android:0c5830255bb0dfaa5d8d90',
    messagingSenderId: '543606157745',
    projectId: 'agenteste-3a825',
    storageBucket: 'agenteste-3a825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9yjEhBGfQuk79Y_5I2CB8WwseinmAYHg',
    appId: '1:543606157745:ios:3a75751215a55d385d8d90',
    messagingSenderId: '543606157745',
    projectId: 'agenteste-3a825',
    storageBucket: 'agenteste-3a825.appspot.com',
    iosBundleId: 'com.example.agencleanProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9yjEhBGfQuk79Y_5I2CB8WwseinmAYHg',
    appId: '1:543606157745:ios:b49b452dd05d4fb45d8d90',
    messagingSenderId: '543606157745',
    projectId: 'agenteste-3a825',
    storageBucket: 'agenteste-3a825.appspot.com',
    iosBundleId: 'com.example.agencleanProject.RunnerTests',
  );
}
